### PR TITLE
Add linux aacrh64 wheel support

### PR DESCRIPTION
**Pull request by odidev**
Added linux aacrh64 wheel support.
Related to #19. @dmuellner Could you please review this PR.

### CODE REVIEW

**Comment by dmuellner** [comment]
Hi, I am happy to include Wheels for aarch64. If I understand the messages from GitHub correctly, Travis gives error messages when trying to build the aarch64 Wheels from your pull request. Any idea what could be the issue?

**Comment by odidev** [comment]
> Travis gives error messages when trying to build the aarch64 Wheels from your pull request. Any idea what could be the issue?

The issue looks to be travis specific and not related to my change. I have no idea why it is hitting. It could be spontaneous issue as didn't seen before even for this repo in my personal travis account.

Please let me know if anything else is required here. Thanks.

**Comment by odidev** [comment]
@dmuellner,  Could you please have a look at this PR? Thanks in advance.

**Comment by dmuellner** [comment]
Aarch64 wheels are included in fastcluster 1.2.2. See https://pypi.org/project/fastcluster/#files.

**Pull request closed without merging**
