### PR TITLE
python 3.7 binary wheels

### PR DESCRIPTION
**Pull request by fgregg**
This PR directs travis and appveyor to build binary wheels for python 3.7

### CODE REVIEW

**Comment by dmuellner** [comment]
Hi Forest,

thanks very much for improving the fastcluster build scripts!

Regarding the fixed NumPy version (the earliest possible for a given Python version), I see two arguments:

Pro: As you said, users will not have problems if the manylinux package was compiled with a later version of NumPy than they have on their system.

Con: We don't get any improvements/bugfixes from later NumPy versions.

As fastcluster only uses the "arrayobject.h" header from NumPy to read and write arrays (which should be very stable functionality), I don't see much potential for trouble from not using the latest NumPy version.

Does this agree with your point of view? In this case I'd be in favor of fixing the NumPy version in the way you did.

A few more questions:

* How did you determine the earliest possible NumPy version in pyproject.toml?

* How does pyproject.toml interfere/interact with `install_requires=["numpy>=1.9"]` in setup.py? (I assume these are two independent statements, one for pip and one for setuptools. Or does pip read setup.py and process the information there?)

* Could you write a comment in pyproject.toml why the NumPy version is fixed? (Basically, the same argument you wrote in the pull request.)

* Nit: no newline at the end of pyproject.toml.

* Out of curiosity: what does `pip install .[test]` do?

**Comment by dmuellner** [comment]
I'd indeed be grateful if you could rebase the commits once the changes are final. Thanks!

**Comment by fgregg** [comment]
Hi Daniel,

Python dynamically links the fastcluster extension to the numpy library. That means that, at run-time, fastcluster will use whatever version of numpy the user has installed locally on their machine.   

> How did you determine the earliest possible NumPy version in pyproject.toml?

For each version of python, I chose the earliest versions of numpy that had binary wheels for that python version for window, mac, and linux. Otherwise building fastcluster would require compiling numpy which would make things much, much slower.

> How does pyproject.toml interfere/interact with install_requires=["numpy>=1.9"] in setup.py? (I assume these are two independent statements, one for pip and one for setuptools. Or does pip read setup.py and process the information there?)

The pyproject.toml describes the environment that is necessary for *building* the fastcluster library. It installs the pyproject.toml specified version of numpy in a temporary build environment, and then setup.py within that build environment. As part of running setup.py, it will compile the fastcluster c extensions. It will also install any run-time dependencies (like install_requires=["numpy">1.9"] in the normal python library install paths. Once it's done building the library, the temporary build environment is removed.

> Out of curiosity: what does pip install .[test] do?

You can specify optional requirements in setup.py. Since scipy is only used in your build environment for testing, I named that optional requirement test.

`pip install .` means install the library that's in the current directory. The [test] also tells pip to install the optional requirements needed  for the tests.

**Comment by dmuellner** [comment]
Thanks!

**Pull request merged**
