### PR TITLE
Migrate to GitHub Actions

### PR DESCRIPTION
**Pull request by NickCrews**
Heavily copied code from both
https://github.com/dedupeio/hcluster/blob/59bc901288bac93a5f61bbe5bab2033b117d00e1/.github/workflows/pythonpackage.yml
and
https://github.com/pypa/cibuildwheel/blob/main/examples/github-deploy.yml

Not totally sure about the configuration of cibuildwheel.
I tried to build it for as many architectures on linux as possible
(using emulation with QEMU) and as many architectures as possible
on MacOS. Only bothered with tje native architecture on Windows.
Not sure if I did that config correctly.

I *think* `auditwheel repair` is getting run in the `cibuildwheel`
action, but not sure?

I disabled building any wheels for pypy (the `pp*` in CIBW_SKIP).
Maybe they could get added back in.

This adds testing for python 3.10, which wasn't there before.
This also always builds wheels on every push and PR, it just
only uploads them to PyPI on tagging. This is different from
before, when building only happened on tags.

Also, automatically publish a release to GitHub in addition to
publishing to PyPI.

### CODE REVIEW

**Comment by NickCrews** [comment]
@fgregg I just did most of this from when I found the problem in https://github.com/dedupeio/dedupe/issues/950, and now I just saw that you did basically the same thing at #28 

There are a few differences between our two techniques, not sure of any pros/cons. For one thing, this should automatically draft a github release, which might be nice. Anyway, pick and choose what you want.

**Comment by fgregg** [comment]
I was waiting on ciwheelbuild's next official list to bug Daniel.

**Comment by NickCrews** [comment]
Yup that makes sense. Then can unify these two PRs with what you actually want.

**Comment by dmuellner** [comment]
Hi Nick and Forest, thanks for preparing the GitHub actions script. This is great!

I merged the pull request, and everything seems to work. One question before I make a new release with the artifacts produced by GitHub Actions: I noticed that the script always specifies a version in the "uses" statements:
```
uses: pypa/cibuildwheel@e9ef3e975082f6f57e64eebd798219c5a7bcf3fd
uses: actions/checkout@v2
uses: pypa/gh-action-pypi-publish@v1.4.2
```

Is it necessary to specify the version of each package, or is there a way to say that I want the latest version?

I also noticed that the script uses `actions/checkout@v1` in one step and `actions/checkout@v2` in another. Is this on purpose?

**Comment by fgregg** [comment]
you can use checkout2 in both places if you want. think this is just due to copy and pasting

**Comment by fgregg** [comment]
also, @dmuellner, if you want you can now disable travis and appveyor, as github actions should cover all the CI you need (linux, mac, and windows)

**Comment by fgregg** [comment]
@NickCrews script will release try try to upload wheels to pypi every time you push a tag that starts with v.

did you add a [pypi API token](https://pypi.org/help/#apitoken) to the [repos secrets](https://docs.github.com/en/actions/security-guides/encrypted-secrets)?   (the secret should be named `pypi_password`

**Comment by dmuellner** [comment]
@fgregg I removed the Appveyor and Travis configs this morning. I also added a PyPi API token as suggested. Everything is working fine.

@NickCrews @fgregg Thanks again for your contribution! This saved me a ton of work. I assume that fastcluster is stable for a while now. Let me know if you find something that is missing or not working.

By the way, I haven't been developing fastcluster any further in the past few years, I only adapted it to changes in its environment (NumPy API, new Python versions etc.). I don't even know how fastcluster's performance compares to current SciPy. Forest, if you feel it is easier for you if you have direct access (no detours, no waiting for me), I'd be happy to hand over fastcluster for adoption (or make you an owner/maintainer). Let me know if you are interested.

**Comment by fgregg** [comment]
thanks! @dmuellner, with the way that the github actions are set up now, if you make me a maintainer on this repo, i can help with getting things released. i’d be happy to do that!

**Pull request merged**
